<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference
      Include="..\Fotbiler.RuleGate.Abstractions\Fotbiler.RuleGate.Abstractions.csproj" />
    <ProjectReference
      Include="..\Fotbiler.RuleGate.Core\Fotbiler.RuleGate.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>

    <PackageId>Fotbiler.RuleGate.AspNetCore</PackageId>
    <Description>ASP.NET Core dependency injection, ClaimsPrincipal mapping, dynamic policy resolution, and resource-based authorization for Fotbiler RuleGate.</Description>
  </PropertyGroup>

  <ItemGroup>
    <None
      Include="$(MSBuildThisFileDirectory)../../README.md"
      Pack="true"
      PackagePath="\"
      Link="README.md" />
  </ItemGroup>

</Project>
