using System.Text;

namespace Fotbiler.RuleGate.Cli.Generation.CSharp;

internal sealed class CSharpCodeGenerator
{
    private const string InvalidNamespaceCode =
        "RGCG001";

    private const string EmptyValueCode =
        "RGCG002";

    private const string InvalidIdentifierCode =
        "RGCG003";

    private const string IdentifierCollisionCode =
        "RGCG004";

    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract",
        "as",
        "base",
        "bool",
        "break",
        "byte",
        "case",
        "catch",
        "char",
        "checked",
        "class",
        "const",
        "continue",
        "decimal",
        "default",
        "delegate",
        "do",
        "double",
        "else",
        "enum",
        "event",
        "explicit",
        "extern",
        "false",
        "finally",
        "fixed",
        "float",
        "for",
        "foreach",
        "goto",
        "if",
        "implicit",
        "in",
        "int",
        "interface",
        "internal",
        "is",
        "lock",
        "long",
        "namespace",
        "new",
        "null",
        "object",
        "operator",
        "out",
        "override",
        "params",
        "private",
        "protected",
        "public",
        "readonly",
        "ref",
        "return",
        "sbyte",
        "sealed",
        "short",
        "sizeof",
        "stackalloc",
        "static",
        "string",
        "struct",
        "switch",
        "this",
        "throw",
        "true",
        "try",
        "typeof",
        "uint",
        "ulong",
        "unchecked",
        "unsafe",
        "ushort",
        "using",
        "virtual",
        "void",
        "volatile",
        "while"
    ];

    public CSharpGenerationResult Generate(
        CSharpGenerationInput input)
    {
        ArgumentNullException.ThrowIfNull(
            input);

        var diagnostics =
            new List<CSharpGenerationDiagnostic>();

        if (!IsValidNamespace(
                input.NamespaceName))
        {
            diagnostics.Add(
                new CSharpGenerationDiagnostic(
                    InvalidNamespaceCode,
                    $"Namespace '{input.NamespaceName}' is not a supported C# namespace."));
        }

        IReadOnlyList<ConstantEntry> policyEntries =
            CreateEntries(
                "policy",
                input.PolicyIds,
                diagnostics);

        IReadOnlyList<ConstantEntry> resourceEntries =
            CreateEntries(
                "resource type",
                input.ResourceTypes,
                diagnostics);

        IReadOnlyList<ConstantEntry> actionEntries =
            CreateEntries(
                "action",
                input.Actions,
                diagnostics);

        if (diagnostics.Count != 0)
        {
            return CSharpGenerationResult.Failure(
                diagnostics);
        }

        var source =
            new StringBuilder();

        source.Append("// <auto-generated />\n");
        source.Append("// Generated by Fotbiler RuleGate. Do not edit.\n");
        source.Append("#nullable enable\n\n");
        source.Append("namespace ");
        source.Append(input.NamespaceName);
        source.Append(";\n\n");

        AppendConstantsClass(
            source,
            "RuleGatePolicies",
            policyEntries);

        source.Append('\n');

        AppendConstantsClass(
            source,
            "RuleGateResourceTypes",
            resourceEntries);

        source.Append('\n');

        AppendConstantsClass(
            source,
            "RuleGateActions",
            actionEntries);

        return CSharpGenerationResult.Success(
            source.ToString());
    }

    private static IReadOnlyList<ConstantEntry> CreateEntries(
        string category,
        IReadOnlyCollection<string> values,
        ICollection<CSharpGenerationDiagnostic> diagnostics)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(
            category);

        ArgumentNullException.ThrowIfNull(
            values);

        ArgumentNullException.ThrowIfNull(
            diagnostics);

        var entries =
            new List<ConstantEntry>();

        foreach (var value in values)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                diagnostics.Add(
                    new CSharpGenerationDiagnostic(
                        EmptyValueCode,
                        $"A {category} value cannot be empty."));

                continue;
            }

            string? identifier =
                CSharpIdentifier.TryCreate(
                    value);

            if (identifier is null)
            {
                diagnostics.Add(
                    new CSharpGenerationDiagnostic(
                        InvalidIdentifierCode,
                        $"The {category} value '{value}' cannot be converted to a C# identifier."));

                continue;
            }

            entries.Add(
                new ConstantEntry(
                    identifier,
                    value));
        }

        ConstantEntry[] distinctEntries =
        [
            .. entries
                .DistinctBy(
                    static entry => entry.Value,
                    StringComparer.Ordinal)
                .OrderBy(
                    static entry => entry.Value,
                    StringComparer.Ordinal)
        ];

        foreach (var collision in
                 distinctEntries
                     .GroupBy(
                         static entry => entry.Identifier,
                         StringComparer.Ordinal)
                     .Where(
                         static group => group.Count() > 1)
                     .OrderBy(
                         static group => group.Key,
                         StringComparer.Ordinal))
        {
            string conflictingValues =
                string.Join(
                    ", ",
                    collision
                        .Select(
                            static entry => $"'{entry.Value}'")
                        .OrderBy(
                            static value => value,
                            StringComparer.Ordinal));

            diagnostics.Add(
                new CSharpGenerationDiagnostic(
                    IdentifierCollisionCode,
                    $"The {category} values {conflictingValues} all map to the C# identifier '{collision.Key}'."));
        }

        return distinctEntries;
    }

    private static void AppendConstantsClass(
        StringBuilder source,
        string className,
        IReadOnlyList<ConstantEntry> entries)
    {
        source.Append("public static class ");
        source.Append(className);
        source.Append("\n{\n");

        foreach (var entry in entries)
        {
            source.Append("    public const string ");
            source.Append(entry.Identifier);
            source.Append(" = \"");
            source.Append(
                EscapeStringLiteral(
                    entry.Value));
            source.Append("\";\n");
        }

        source.Append("}\n");
    }

    private static bool IsValidNamespace(
        string namespaceName)
    {
        if (string.IsNullOrWhiteSpace(namespaceName))
        {
            return false;
        }

        string[] segments =
            namespaceName.Split(
                '.',
                StringSplitOptions.None);

        return segments.All(
            IsValidNamespaceSegment);
    }

    private static bool IsValidNamespaceSegment(
        string segment)
    {
        if (segment.Length == 0
            || CSharpKeywords.Contains(segment))
        {
            return false;
        }

        if (!IsAsciiLetter(segment[0])
            && segment[0] != '_')
        {
            return false;
        }

        return segment
            .Skip(1)
            .All(
                static character =>
                    IsAsciiLetter(character)
                    || char.IsDigit(character)
                    || character == '_');
    }

    private static bool IsAsciiLetter(
        char character) =>
        character is >= 'A' and <= 'Z'
        or >= 'a' and <= 'z';

    private static string EscapeStringLiteral(
        string value)
    {
        var escaped =
            new StringBuilder(
                value.Length);

        foreach (var character in value)
        {
            _ = character switch
            {
                '\\' => escaped.Append("\\\\"),
                '"' => escaped.Append("\\\""),
                '\0' => escaped.Append("\\0"),
                '\a' => escaped.Append("\\a"),
                '\b' => escaped.Append("\\b"),
                '\f' => escaped.Append("\\f"),
                '\n' => escaped.Append("\\n"),
                '\r' => escaped.Append("\\r"),
                '\t' => escaped.Append("\\t"),
                '\v' => escaped.Append("\\v"),
                < ' ' => escaped.Append(
                    $"\\u{(int)character:x4}"),
                '\u2028' or '\u2029' => escaped.Append(
                    $"\\u{(int)character:x4}"),
                _ => escaped.Append(character)
            };
        }

        return escaped.ToString();
    }

    private sealed record ConstantEntry(
        string Identifier,
        string Value);
}
