packages:
  - compatibility/angular-modern-builder
  - src/Fotbiler.RuleGate.Client
  - src/Fotbiler.RuleGate.Angular
  - samples/document-approval/web

linkWorkspacePackages: false

allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  lmdb: false
  msgpackr-extract: false

minimumReleaseAgeExclude:
  - '@angular/common@20.3.27'
  - '@angular/compiler@20.3.27'
  - '@angular/compiler-cli@20.3.27'
  - '@angular/core@20.3.27'
  - '@angular/router@20.3.27'
  - '@fotbiler/rulegate-angular@0.9.0-preview.4'
  - '@fotbiler/rulegate-client@0.9.0-preview.4'
