<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(RuleGateAspNetCoreTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <EnablePackageValidation>false</EnablePackageValidation>
    <PackageValidationBaselineVersion />
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RuleGatePackageVersion Condition="'$(RuleGatePackageVersion)' == ''">1.0.0-rc.1</RuleGatePackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="Fotbiler.RuleGate.AspNetCore"
      Version="$(RuleGatePackageVersion)" />

    <PackageReference
      Include="Fotbiler.RuleGate.Manifest"
      Version="$(RuleGatePackageVersion)" />
  </ItemGroup>

</Project>
