#!/usr/bin/env node

import { randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import { parseDocument } from 'yaml';

export const ruleGateAngularExitCodes = Object.freeze({
  success: 0,
  invalid: 1,
  usage: 2,
  unexpected: 3,
});

const DEFAULT_MANIFEST_PATH = 'rulegate.yaml';
const GENERATED_HEADER = '// <auto-generated />\n// Generated by RuleGate. Do not edit.\n\n';

const HELP = `RuleGate Angular identifier generator

Usage:
  rulegate-angular generate [file] [--output <file>] [--check]

Arguments:
  file                 Manifest path. Defaults to rulegate.yaml.

Options:
  -o, --output <file>  Output file. Writes TypeScript to stdout when omitted.
  --check              Verify that --output is current without modifying it.
  -h, --help           Show help.
`;

export async function runRuleGateAngularCli(
  argumentsList,
  io = {
    stdout: process.stdout,
    stderr: process.stderr,
  },
) {
  try {
    const options = parseArguments(argumentsList);

    if (options.help) {
      io.stdout.write(HELP);
      return ruleGateAngularExitCodes.success;
    }

    const manifestPath = resolve(options.manifestPath);
    const manifestText = await readFile(manifestPath, 'utf8');
    const generation = generateRuleGateTypeScript(manifestText, manifestPath);

    if (!generation.success) {
      writeDiagnostics(io.stderr, manifestPath, generation.diagnostics);
      return ruleGateAngularExitCodes.invalid;
    }

    if (!options.outputPath) {
      io.stdout.write(generation.source);
      return ruleGateAngularExitCodes.success;
    }

    const outputPath = resolve(options.outputPath);

    if (options.check) {
      return await checkOutput(outputPath, generation.source, io);
    }

    await writeAtomically(outputPath, generation.source);
    io.stdout.write(`RuleGate TypeScript generated.\n\n`);
    io.stdout.write(`Manifest: ${manifestPath}\n`);
    io.stdout.write(`Output: ${outputPath}\n`);
    io.stdout.write(`Policies: ${generation.counts.policies}\n`);
    io.stdout.write(`Permissions: ${generation.counts.permissions}\n`);

    return ruleGateAngularExitCodes.success;
  } catch (error) {
    if (error instanceof RuleGateAngularUsageError) {
      io.stderr.write(`error: ${error.message}\n\n${HELP}`);
      return ruleGateAngularExitCodes.usage;
    }

    if (error && typeof error === 'object' && error.code === 'ENOENT') {
      io.stderr.write(`error: input or output file was not found.\n`);
      return ruleGateAngularExitCodes.invalid;
    }

    io.stderr.write('error: unexpected RuleGate Angular generator failure.\n');
    return ruleGateAngularExitCodes.unexpected;
  }
}

export function generateRuleGateTypeScript(manifestText, manifestPath = 'rulegate.yaml') {
  const diagnostics = [];
  const document = parseDocument(manifestText, {
    prettyErrors: true,
    strict: true,
    uniqueKeys: true,
  });

  for (const error of document.errors) {
    diagnostics.push(`YAML: ${error.message}`);
  }

  if (diagnostics.length !== 0) {
    return failure(diagnostics);
  }

  let manifest;

  try {
    manifest = document.toJS({ maxAliasCount: 0 });
  } catch (error) {
    diagnostics.push(`YAML: ${error instanceof Error ? error.message : 'invalid aliases.'}`);
    return failure(diagnostics);
  }

  const identifiers = collectManifestIdentifiers(manifest, diagnostics);

  if (!identifiers || diagnostics.length !== 0) {
    return failure(diagnostics);
  }

  const groups = {
    policies: createEntries('policy', identifiers.policies, diagnostics),
    permissions: createEntries('permission', identifiers.permissions, diagnostics),
    resourceTypes: createEntries('resource type', identifiers.resourceTypes, diagnostics),
    actions: createEntries('action', identifiers.actions, diagnostics),
  };

  if (diagnostics.length !== 0) {
    return failure(diagnostics);
  }

  const source =
    GENERATED_HEADER +
    `export const RuleGateIdentifiers = {\n` +
    appendGroup('policies', groups.policies) +
    appendGroup('permissions', groups.permissions) +
    appendGroup('resourceTypes', groups.resourceTypes) +
    appendGroup('actions', groups.actions) +
    `} as const;\n\n` +
    appendValueType('RuleGatePolicy', 'policies') +
    appendValueType('RuleGatePermission', 'permissions') +
    appendValueType('RuleGateResourceType', 'resourceTypes') +
    appendValueType('RuleGateAction', 'actions');

  return Object.freeze({
    success: true,
    source,
    diagnostics: Object.freeze([]),
    manifestPath,
    counts: Object.freeze({
      policies: groups.policies.length,
      permissions: groups.permissions.length,
      resourceTypes: groups.resourceTypes.length,
      actions: groups.actions.length,
    }),
  });
}

function parseArguments(argumentsList) {
  if (
    argumentsList.length === 0 ||
    argumentsList.includes('--help') ||
    argumentsList.includes('-h')
  ) {
    return { help: true };
  }

  if (argumentsList[0] !== 'generate') {
    throw new RuleGateAngularUsageError(`unknown command '${argumentsList[0]}'.`);
  }

  let manifestPath = DEFAULT_MANIFEST_PATH;
  let outputPath;
  let check = false;
  let hasManifestPath = false;

  for (let index = 1; index < argumentsList.length; index += 1) {
    const argument = argumentsList[index];

    if (argument === '--output' || argument === '-o') {
      outputPath = argumentsList[index + 1];

      if (!outputPath || outputPath.startsWith('-')) {
        throw new RuleGateAngularUsageError(`${argument} requires a file path.`);
      }

      index += 1;
      continue;
    }

    if (argument === '--check') {
      check = true;
      continue;
    }

    if (argument.startsWith('-')) {
      throw new RuleGateAngularUsageError(`unknown option '${argument}'.`);
    }

    if (hasManifestPath) {
      throw new RuleGateAngularUsageError('only one manifest path is supported.');
    }

    manifestPath = argument;
    hasManifestPath = true;
  }

  if (check && !outputPath) {
    throw new RuleGateAngularUsageError('--check requires --output.');
  }

  return { help: false, manifestPath, outputPath, check };
}

function collectManifestIdentifiers(manifest, diagnostics) {
  if (!isPlainObject(manifest)) {
    diagnostics.push('Manifest root must be an object.');
    return null;
  }

  if (manifest.schemaVersion !== 1) {
    diagnostics.push("Manifest 'schemaVersion' must be 1.");
  }

  if (!Array.isArray(manifest.policies) || manifest.policies.length === 0) {
    diagnostics.push("Manifest 'policies' must be a non-empty array.");
    return null;
  }

  const policies = new Set();
  const permissions = new Set();
  const resourceTypes = new Set();
  const actions = new Set();
  const routes = new Set();

  manifest.policies.forEach((policy, index) => {
    const path = `policies[${index}]`;

    if (!isPlainObject(policy)) {
      diagnostics.push(`${path} must be an object.`);
      return;
    }

    const id = readIdentifier(policy.id, `${path}.id`, diagnostics);
    const resourceType = readIdentifier(policy.resourceType, `${path}.resourceType`, diagnostics);
    const action = readIdentifier(policy.action, `${path}.action`, diagnostics);

    if (id) {
      if (policies.has(id)) {
        diagnostics.push(`Duplicate policy identifier '${id}'.`);
      }

      policies.add(id);
    }

    if (resourceType) {
      resourceTypes.add(resourceType);
    }

    if (action) {
      actions.add(action);
    }

    if (resourceType && action) {
      const route = `${resourceType}\u0000${action}`;

      if (routes.has(route)) {
        diagnostics.push(`Duplicate policy route '${resourceType}:${action}'.`);
      }

      routes.add(route);
    }

    collectPermissions(policy.requirement, `${path}.requirement`, permissions, diagnostics);
  });

  return { policies, permissions, resourceTypes, actions };
}

function collectPermissions(requirement, path, permissions, diagnostics) {
  if (!isPlainObject(requirement)) {
    diagnostics.push(`${path} must be an object.`);
    return;
  }

  const kinds = ['permission', 'role', 'attribute', 'all', 'any', 'not'].filter(
    (kind) => requirement[kind] !== undefined && requirement[kind] !== null,
  );

  if (kinds.length !== 1) {
    diagnostics.push(`${path} must define exactly one requirement kind.`);
    return;
  }

  const kind = kinds[0];

  if (kind === 'permission') {
    const permission = readIdentifier(requirement.permission, `${path}.permission`, diagnostics);

    if (permission) {
      permissions.add(permission);
    }

    return;
  }

  if (kind === 'role') {
    readIdentifier(requirement.role, `${path}.role`, diagnostics);
    return;
  }

  if (kind === 'attribute') {
    if (!isPlainObject(requirement.attribute)) {
      diagnostics.push(`${path}.attribute must be an object.`);
    }

    return;
  }

  if (kind === 'not') {
    collectPermissions(requirement.not, `${path}.not`, permissions, diagnostics);
    return;
  }

  const children = requirement[kind];

  if (!Array.isArray(children) || children.length === 0) {
    diagnostics.push(`${path}.${kind} must be a non-empty array.`);
    return;
  }

  children.forEach((child, index) =>
    collectPermissions(child, `${path}.${kind}[${index}]`, permissions, diagnostics),
  );
}

function createEntries(category, values, diagnostics) {
  const entries = [...values]
    .sort(compareOrdinal)
    .map((value) => ({ value, identifier: createTypeScriptIdentifier(value) }));

  for (const entry of entries) {
    if (!entry.identifier) {
      diagnostics.push(`The ${category} '${entry.value}' cannot become a TypeScript identifier.`);
    }
  }

  const byIdentifier = new Map();

  for (const entry of entries) {
    if (!entry.identifier) {
      continue;
    }

    const conflicting = byIdentifier.get(entry.identifier) ?? [];
    conflicting.push(entry.value);
    byIdentifier.set(entry.identifier, conflicting);
  }

  for (const [identifier, conflicting] of byIdentifier) {
    if (conflicting.length > 1) {
      diagnostics.push(
        `The ${category} values ${conflicting.map((value) => `'${value}'`).join(', ')} ` +
          `all map to '${identifier}'.`,
      );
    }
  }

  return entries;
}

function createTypeScriptIdentifier(value) {
  const segments = value.match(/[A-Za-z0-9]+/g);

  if (!segments || segments.length === 0) {
    return null;
  }

  const [first, ...remaining] = segments;
  let identifier =
    first.toLowerCase() +
    remaining.map((segment) => segment[0].toUpperCase() + segment.slice(1).toLowerCase()).join('');

  if (/^[0-9]/.test(identifier)) {
    identifier = `_${identifier}`;
  }

  if (identifier === '__proto__' || identifier === 'constructor' || identifier === 'prototype') {
    identifier = `_${identifier}`;
  }

  return identifier;
}

function appendGroup(groupName, entries) {
  let source = `  ${groupName}: {\n`;

  for (const entry of entries) {
    source += `    ${entry.identifier}: ${escapeTypeScriptString(entry.value)},\n`;
  }

  return source + `  },\n`;
}

function appendValueType(typeName, groupName) {
  return (
    `export type ${typeName} =\n` +
    `  (typeof RuleGateIdentifiers.${groupName})` +
    `[keyof typeof RuleGateIdentifiers.${groupName}];\n`
  );
}

function escapeTypeScriptString(value) {
  return JSON.stringify(value).replaceAll('\u2028', '\\u2028').replaceAll('\u2029', '\\u2029');
}

function readIdentifier(value, path, diagnostics) {
  if (typeof value !== 'string' || value.length === 0 || value.trim() !== value) {
    diagnostics.push(`${path} must be a non-empty, non-padded string.`);
    return null;
  }

  return value;
}

function isPlainObject(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function compareOrdinal(left, right) {
  return left < right ? -1 : left > right ? 1 : 0;
}

function failure(diagnostics) {
  return Object.freeze({
    success: false,
    source: null,
    diagnostics: Object.freeze([...diagnostics]),
    counts: null,
  });
}

function writeDiagnostics(error, manifestPath, diagnostics) {
  error.write(`RuleGate TypeScript generation failed.\n\nFile: ${manifestPath}\n`);

  for (const diagnostic of diagnostics) {
    error.write(`\n  ${diagnostic}\n`);
  }

  error.write(`\n${diagnostics.length} error(s) found.\n`);
}

async function checkOutput(outputPath, source, io) {
  let actual;

  try {
    actual = await readFile(outputPath);
  } catch (error) {
    if (error && typeof error === 'object' && error.code === 'ENOENT') {
      io.stderr.write(`RuleGate TypeScript output is missing.\n\nOutput: ${outputPath}\n`);
      return ruleGateAngularExitCodes.invalid;
    }

    throw error;
  }

  if (!actual.equals(Buffer.from(source, 'utf8'))) {
    io.stderr.write(`RuleGate TypeScript output is stale.\n\nOutput: ${outputPath}\n`);
    return ruleGateAngularExitCodes.invalid;
  }

  io.stdout.write(`RuleGate TypeScript output is current.\n\nOutput: ${outputPath}\n`);
  return ruleGateAngularExitCodes.success;
}

async function writeAtomically(outputPath, source) {
  const directory = dirname(outputPath);
  await mkdir(directory, { recursive: true });

  const temporaryPath = resolve(
    directory,
    `.${basename(outputPath)}.${process.pid}.${randomUUID()}.tmp`,
  );

  try {
    await writeFile(temporaryPath, source, { encoding: 'utf8', flag: 'wx' });
    await rename(temporaryPath, outputPath);
  } finally {
    await rm(temporaryPath, { force: true });
  }
}

class RuleGateAngularUsageError extends Error {}

const isEntryPoint =
  process.argv[1] !== undefined && import.meta.url === pathToFileURL(resolve(process.argv[1])).href;

if (isEntryPoint) {
  process.exitCode = await runRuleGateAngularCli(process.argv.slice(2));
}
