<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(RuleGateAspNetCoreTargetFrameworks)</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <EnablePackageValidation>false</EnablePackageValidation>
    <PackageValidationBaselineVersion />
    <RuleGatePackageVersion Condition="'$(RuleGatePackageVersion)' == ''">0.9.0-preview.4</RuleGatePackageVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="Fotbiler.RuleGate.Keycloak"
      Version="$(RuleGatePackageVersion)" />
  </ItemGroup>

</Project>
