<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>$(RuleGateTargetFrameworks)</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="Fotbiler.RuleGate.Keycloak"
      Version="0.8.0-preview.2" />
  </ItemGroup>

</Project>
