using Fotbiler.RuleGate.Cli.Generation.CSharp;

namespace Fotbiler.RuleGate.Cli.Tests;

public sealed class CSharpCodeGeneratorTests
{
    private const string ExpectedSource =
        "// <auto-generated />\n"
        + "// Generated by RuleGate. Do not edit.\n"
        + "#nullable enable\n"
        + "\n"
        + "namespace Sample.Authorization;\n"
        + "\n"
        + "public static class RuleGatePolicies\n"
        + "{\n"
        + "    public const string DocumentsRead = \"documents.read\";\n"
        + "    public const string OrdersUpdate = \"orders.update\";\n"
        + "}\n"
        + "\n"
        + "public static class RuleGateResourceTypes\n"
        + "{\n"
        + "    public const string Document = \"document\";\n"
        + "    public const string Order = \"order\";\n"
        + "}\n"
        + "\n"
        + "public static class RuleGateActions\n"
        + "{\n"
        + "    public const string Read = \"read\";\n"
        + "    public const string Update = \"update\";\n"
        + "}\n";

    private readonly CSharpCodeGenerator generator =
        new();

    [Fact]
    public void Generate_ProducesExpectedDeterministicSource()
    {
        CSharpGenerationInput input =
            CreateInput();

        CSharpGenerationResult result =
            generator.Generate(
                input);

        Assert.True(
            result.IsSuccess);

        Assert.Empty(
            result.Diagnostics);

        Assert.Equal(
            ExpectedSource,
            result.Source);
    }

    [Fact]
    public void Generate_IsIndependentOfInputOrdering()
    {
        var input =
            new CSharpGenerationInput(
                "Sample.Authorization",
                [
                    "orders.update",
                    "documents.read"
                ],
                [
                    "order",
                    "document"
                ],
                [
                    "update",
                    "read"
                ]);

        CSharpGenerationResult result =
            generator.Generate(
                input);

        Assert.True(
            result.IsSuccess);

        Assert.Equal(
            ExpectedSource,
            result.Source);
    }

    [Fact]
    public void Generate_NormalizesSeparatorsAndLeadingDigits()
    {
        var input =
            new CSharpGenerationInput(
                "Sample.Authorization",
                [
                    "123.orders-read"
                ],
                [
                    "sales-order"
                ],
                [
                    "read_all"
                ]);

        CSharpGenerationResult result =
            generator.Generate(
                input);

        Assert.True(
            result.IsSuccess);

        Assert.Contains(
            "public const string _123OrdersRead = \"123.orders-read\";",
            result.Source,
            StringComparison.Ordinal);

        Assert.Contains(
            "public const string SalesOrder = \"sales-order\";",
            result.Source,
            StringComparison.Ordinal);

        Assert.Contains(
            "public const string ReadAll = \"read_all\";",
            result.Source,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_FailsClosedOnIdentifierCollision()
    {
        var input =
            new CSharpGenerationInput(
                "Sample.Authorization",
                [
                    "orders.read",
                    "orders-read"
                ],
                [
                    "order"
                ],
                [
                    "read"
                ]);

        CSharpGenerationResult result =
            generator.Generate(
                input);

        Assert.False(
            result.IsSuccess);

        Assert.Null(
            result.Source);

        CSharpGenerationDiagnostic diagnostic =
            Assert.Single(
                result.Diagnostics);

        Assert.Equal(
            "RGCG004",
            diagnostic.Code);

        Assert.Contains(
            "OrdersRead",
            diagnostic.Message,
            StringComparison.Ordinal);
    }

    [Theory]
    [InlineData("")]
    [InlineData("Sample..Authorization")]
    [InlineData("Sample.Authorization-Api")]
    [InlineData("123.Sample")]
    [InlineData("namespace.Sample")]
    public void Generate_RejectsUnsupportedNamespace(
        string namespaceName)
    {
        var input =
            new CSharpGenerationInput(
                namespaceName,
                [
                    "documents.read"
                ],
                [
                    "document"
                ],
                [
                    "read"
                ]);

        CSharpGenerationResult result =
            generator.Generate(
                input);

        Assert.False(
            result.IsSuccess);

        Assert.Null(
            result.Source);

        Assert.Contains(
            result.Diagnostics,
            static diagnostic =>
                diagnostic.Code == "RGCG001");
    }

    [Fact]
    public void Generate_EscapesCSharpStringLiterals()
    {
        var input =
            new CSharpGenerationInput(
                "Sample.Authorization",
                [
                    "documents.\"read\"\\line\nnext"
                ],
                [
                    "document"
                ],
                [
                    "read"
                ]);

        CSharpGenerationResult result =
            generator.Generate(
                input);

        Assert.True(
            result.IsSuccess);

        Assert.Contains(
            "\"documents.\\\"read\\\"\\\\line\\nnext\"",
            result.Source,
            StringComparison.Ordinal);
    }

    [Fact]
    public void Generate_UsesUtf8FriendlyLfOnlySourceShape()
    {
        CSharpGenerationResult result =
            generator.Generate(
                CreateInput());

        Assert.True(
            result.IsSuccess);

        string source =
            Assert.IsType<string>(
                result.Source);

        Assert.DoesNotContain(
            '\r',
            source);

        Assert.EndsWith(
            "\n",
            source,
            StringComparison.Ordinal);
    }

    private static CSharpGenerationInput CreateInput() =>
        new(
            "Sample.Authorization",
            [
                "documents.read",
                "orders.update"
            ],
            [
                "document",
                "order"
            ],
            [
                "read",
                "update"
            ]);
}
