using System.Globalization;

using Fotbiler.RuleGate.Cli;
using Fotbiler.RuleGate.Manifest.Loading;
using Fotbiler.RuleGate.Manifest.Validation;

namespace Fotbiler.RuleGate.Cli.Tests;

public sealed class GenerateCSharpCommandTests
{
    private const string ValidManifest =
        """
        schemaVersion: 1

        application:
          id: generation-cli-tests
          name: Generation CLI Tests

        policies:
          - id: orders.update
            resourceType: order
            action: update
            requirement:
              permission: ORDERS.UPDATE

          - id: documents.read
            resourceType: document
            action: read
            requirement:
              permission: DOCUMENTS.READ
        """;

    private const string CollisionManifest =
        """
        schemaVersion: 1

        application:
          id: generation-collision-cli-tests
          name: Generation Collision CLI Tests

        policies:
          - id: orders.read
            resourceType: order
            action: read
            requirement:
              permission: ORDERS.READ

          - id: orders-read
            resourceType: order
            action: inspect
            requirement:
              permission: ORDERS.INSPECT
        """;

    [Fact]
    public async Task GenerateCSharp_HelpShowsContract()
    {
        CliResult result =
            await RunAsync(
                "generate",
                "csharp",
                "--help");

        Assert.Equal(
            0,
            result.ExitCode);

        Assert.Contains(
            "--namespace",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Contains(
            "--output",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Contains(
            "[<file>]",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Empty(
            result.StandardError);
    }

    [Fact]
    public async Task GenerateCSharp_WritesPureSourceToStandardOutput()
    {
        using var directory =
            new TemporaryDirectory();

        string manifestPath =
            directory.WriteFile(
                "rulegate.yaml",
                ValidManifest);

        CliResult result =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath,
                "--namespace",
                "Sample.Authorization");

        Assert.Equal(
            0,
            result.ExitCode);

        Assert.StartsWith(
            "// <auto-generated />\n",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Contains(
            "namespace Sample.Authorization;",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Contains(
            "public const string DocumentsRead = \"documents.read\";",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Contains(
            "public const string OrdersUpdate = \"orders.update\";",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.DoesNotContain(
            "RuleGate C# source generated.",
            result.StandardOutput,
            StringComparison.Ordinal);

        Assert.Empty(
            result.StandardError);
    }

    [Fact]
    public async Task GenerateCSharp_WritesDeterministicOutputFile()
    {
        using var directory =
            new TemporaryDirectory();

        string manifestPath =
            directory.WriteFile(
                "rulegate.yaml",
                ValidManifest);

        string firstOutputPath =
            Path.Combine(
                directory.Path,
                "generated",
                "RuleGate.g.cs");

        string secondOutputPath =
            Path.Combine(
                directory.Path,
                "generated",
                "RuleGate.Second.g.cs");

        CliResult firstResult =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath,
                "--namespace",
                "Sample.Authorization",
                "--output",
                firstOutputPath);

        CliResult secondResult =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath,
                "--namespace",
                "Sample.Authorization",
                "--output",
                secondOutputPath);

        Assert.Equal(
            0,
            firstResult.ExitCode);

        Assert.Equal(
            0,
            secondResult.ExitCode);

        Assert.True(
            File.Exists(
                firstOutputPath));

        Assert.True(
            File.Exists(
                secondOutputPath));

        string firstSource =
            await File.ReadAllTextAsync(
                firstOutputPath);

        string secondSource =
            await File.ReadAllTextAsync(
                secondOutputPath);

        Assert.Equal(
            firstSource,
            secondSource);

        Assert.DoesNotContain(
            '\r',
            firstSource);

        Assert.Contains(
            Path.GetFullPath(
                firstOutputPath),
            firstResult.StandardOutput,
            StringComparison.Ordinal);

        Assert.Contains(
            "Policies: 2",
            firstResult.StandardOutput,
            StringComparison.Ordinal);

        Assert.Empty(
            firstResult.StandardError);
    }

    [Fact]
    public async Task GenerateCSharp_RequiresNamespace()
    {
        using var directory =
            new TemporaryDirectory();

        string manifestPath =
            directory.WriteFile(
                "rulegate.yaml",
                ValidManifest);

        CliResult result =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath);

        Assert.Equal(
            2,
            result.ExitCode);

        Assert.Contains(
            "error:",
            result.StandardError,
            StringComparison.Ordinal);

        Assert.Empty(
            result.StandardOutput);
    }

    [Fact]
    public async Task GenerateCSharp_InvalidManifestPreservesExistingOutput()
    {
        using var directory =
            new TemporaryDirectory();

        string manifestPath =
            directory.WriteFile(
                "invalid.yaml",
                """
                schemaVersion: 999

                application:
                  id: invalid-generation-cli-tests
                  name: Invalid Generation CLI Tests

                policies: []
                """);

        string outputPath =
            directory.WriteFile(
                "RuleGate.g.cs",
                "existing-content");

        CliResult result =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath,
                "--namespace",
                "Sample.Authorization",
                "--output",
                outputPath);

        Assert.Equal(
            1,
            result.ExitCode);

        Assert.Contains(
            ManifestValidationCodes
                .UnsupportedSchemaVersion,
            result.StandardError,
            StringComparison.Ordinal);

        Assert.Equal(
            "existing-content",
            await File.ReadAllTextAsync(
                outputPath));

        Assert.Empty(
            result.StandardOutput);
    }

    [Fact]
    public async Task GenerateCSharp_MissingManifestReturnsLoadFailure()
    {
        using var directory =
            new TemporaryDirectory();

        string manifestPath =
            Path.Combine(
                directory.Path,
                "missing.yaml");

        CliResult result =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath,
                "--namespace",
                "Sample.Authorization");

        Assert.Equal(
            1,
            result.ExitCode);

        Assert.Contains(
            ManifestLoadCodes.FileNotFound,
            result.StandardError,
            StringComparison.Ordinal);

        Assert.Empty(
            result.StandardOutput);
    }

    [Fact]
    public async Task GenerateCSharp_CollisionPreservesExistingOutput()
    {
        using var directory =
            new TemporaryDirectory();

        string manifestPath =
            directory.WriteFile(
                "collision.yaml",
                CollisionManifest);

        string outputPath =
            directory.WriteFile(
                "RuleGate.g.cs",
                "existing-content");

        CliResult result =
            await RunAsync(
                "generate",
                "csharp",
                manifestPath,
                "--namespace",
                "Sample.Authorization",
                "--output",
                outputPath);

        Assert.Equal(
            1,
            result.ExitCode);

        Assert.Contains(
            "RGCG004",
            result.StandardError,
            StringComparison.Ordinal);

        Assert.Contains(
            "OrdersRead",
            result.StandardError,
            StringComparison.Ordinal);

        Assert.Equal(
            "existing-content",
            await File.ReadAllTextAsync(
                outputPath));

        Assert.Empty(
            result.StandardOutput);
    }

    [Fact]
    public async Task GenerateCSharp_DefaultManifestDiscoveryWorks()
    {
        using var directory =
            new TemporaryDirectory();

        directory.WriteFile(
            "rulegate.yaml",
            ValidManifest);

        string originalDirectory =
            Environment.CurrentDirectory;

        try
        {
            Environment.CurrentDirectory =
                directory.Path;

            CliResult result =
                await RunAsync(
                    "generate",
                    "csharp",
                    "--namespace",
                    "Sample.Authorization");

            Assert.Equal(
                0,
                result.ExitCode);

            Assert.Contains(
                "DocumentsRead",
                result.StandardOutput,
                StringComparison.Ordinal);

            Assert.Empty(
                result.StandardError);
        }
        finally
        {
            Environment.CurrentDirectory =
                originalDirectory;
        }
    }

    private static async Task<CliResult> RunAsync(
        params string[] arguments)
    {
        using var output =
            new StringWriter(
                CultureInfo.InvariantCulture);

        using var error =
            new StringWriter(
                CultureInfo.InvariantCulture);

        int exitCode =
            await RuleGateCliApplication.RunAsync(
                arguments,
                output,
                error);

        return new CliResult(
            exitCode,
            output.ToString(),
            error.ToString());
    }

    private sealed record CliResult(
        int ExitCode,
        string StandardOutput,
        string StandardError);

    private sealed class TemporaryDirectory :
        IDisposable
    {
        public TemporaryDirectory()
        {
            Path =
                System.IO.Path.Combine(
                    System.IO.Path.GetTempPath(),
                    "rulegate-generation-cli-tests-" +
                    Guid.NewGuid()
                        .ToString("N"));

            Directory.CreateDirectory(
                Path);
        }

        public string Path
        {
            get;
        }

        public string WriteFile(
            string fileName,
            string content)
        {
            string path =
                System.IO.Path.Combine(
                    Path,
                    fileName);

            string? directory =
                System.IO.Path.GetDirectoryName(
                    path);

            if (directory is not null)
            {
                Directory.CreateDirectory(
                    directory);
            }

            File.WriteAllText(
                path,
                content);

            return path;
        }

        public void Dispose()
        {
            if (Directory.Exists(
                    Path))
            {
                Directory.Delete(
                    Path,
                    recursive: true);
            }
        }
    }
}
